#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

APP_NAME="TimeProfiler"
APP_UI_TEST_SCHEME="TimeProfilerUITests"
APP_RUNNER_NAME="$APP_UI_TEST_SCHEME-Runner"
APP_DIR="$SCRIPT_DIR"
APP_WORKSPACE="$APP_DIR/TimeProfiler.xcworkspace"
APP_UI_TEST_PRINCIPAL_CLASS="PrincipalClass"
APP_UI_TEST_PRINCIPAL_CLASS_FILE="$APP_DIR/$APP_UI_TEST_SCHEME/$APP_UI_TEST_PRINCIPAL_CLASS.swift"
APP_UI_TEST_NAMES=( \
 	"$APP_UI_TEST_SCHEME/TimeProfilerUITests/testExample" \
)
DEVICE_UDID="adc1f1d241503473a9bc29696a89f37b87aef72c" # Enter 

bash "$SCRIPT_DIR/TimeProfilerHelperScripts/start"    \
        "$APP_NAME" \
        "$APP_RUNNER_NAME" \
        "$APP_WORKSPACE" \
        "$APP_UI_TEST_SCHEME" \
        ".time-profiler-tester-reports" \
        ".time-profiler-tester-build" \
        "$DEVICE_UDID" \
        "$APP_UI_TEST_PRINCIPAL_CLASS_FILE" \
        "$APP_UI_TEST_PRINCIPAL_CLASS" \
        "$APP_UI_TEST_NAMES"
